10-process_and_pid_file

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,13 +1,35 @@
 #!/usr/bin/env bash
-#display string indefinitely, withstand SIGTERM
 
-echo $$ > /var/run/holbertonscript.pid
+pid_file="/var/run/holbertonscript.pid"
 
-trap 'echo "I hate the kill command" && rm /var/run/holbertonscript.pid  && exit' SIGTERM
-trap 'echo "Y U no love me?!" && rm /var/run/holbertonscript.pid && exit' SIGINT
+# Function to handle SIGTERM signal
+sigterm_handler() {
+    echo "I hate the kill command"
+    cleanup_and_exit
+}
 
-i="1"
-while [ $i == 1 ]; do
+# Function to handle SIGQUIT signal
+sigquit_handler() {
+    cleanup_and_exit
+}
+
+# Function to perform cleanup and exit the script
+cleanup_and_exit() {
+    echo "Cleaning up and terminating the script..."
+    rm -f "$pid_file"  # Delete the PID file
+    exit 0
+}
+
+# Register signal handlers
+trap 'sigterm_handler' SIGTERM
+trap 'sigquit_handler' SIGQUIT
+
+# Store the script's PID in the file
+echo $$ > "$pid_file"
+
+# Display the string indefinitely
+while true; do
     echo "To infinity and beyond"
     sleep 2
 done
+
